const express = require('express') 
const app = express() 
const cors = require('cors')
const connectToDb = require('./Database/db')
require('dotenv').config()
const PORT = process.env.PORT
connectToDb()
app.use(cors())
app.use(express.urlencoded({extended: false}))
app.use('/', require('./Routes/api/router'))
app.use(express.json())
app.listen(PORT, () => console.log('Server listening on port 5000'))
